branches:
  only:
    - test-branch
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
env:
  global:
    - SOME_GLOBAL_VAR="I am a global var"

before_script:
  - set -e
  - echo "before_script step"
script:
  - echo "in script step"
  - echo "commit " ${TRAVIS_COMMIT}
  - echo "branch " ${TRAVIS_BRANCH}
  - echo "tag " ${TRAVIS_TAG}

deploy:
  - provider: script
    script: echo test-branch
    on:
      branch: test-branch
  - provider: script
    script: echo "deploy master detected"
    on:
      branch: master

  - provider: script
    script: echo "is master and tag is on"
    on:
      tags: true
      branch: master
    
  - provider: script
    script: echo "I react only to tags and the tag is ${TRAVIS_TAG}"
    on:
      tags: true
